services:
  grafana:
    image: grafana/grafana:latest-distroless
    volumes:
      - grafana:/var/lib/grafana/
    ports:
      - "3001:3000"
  prometheus:
    image: prom/prometheus:v3
    volumes:
      - prometheus:/prometheus

volumes:
  prometheus: {}
  grafana: {}
